/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'holavson' at '29/10/16 19:20' with Gradle 3.1
 *
 * @author holavson, @date 29/10/16 19:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
